carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

]

greatbuy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),

]

carts/models.py
from django.db import models

# Create your models here.
from store.models import Product, Variation


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from django.urls import reverse

from category.models import Category


# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=400, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choice =(
    ('color', 'color'),
    ('size', 'size'),
    )


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

carts/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from carts.models import Cart, CartItem
from store.models import Product, Variation


# Create your views here.
# Adicionar um _ antes de uma função faz ela se tornar privada
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()

    return  cart


def add_to_cart(request, product_id):

    product = Product.objects.get(id=product_id)
    product_variation = []

    if request.method == 'POST':
        #esse for serve para checar todas as infos que virão no POST
        for item in request.POST:
            key = item
            value = request.POST[key]

            try:
                variation = Variation.objects.get(product=product, variation_category__iexact=key,
                                                  variation_value__iexact=value)
                product_variation.append(variation)

            except:
                pass

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))

    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))

    cart.save()

    cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()

    if cart_item_exists:
        cart_item = CartItem.objects.filter(product=product, cart=cart)

        # variações existentes -> banco de dados
        # variação atual -> product_variation
        # item_id -> banco de dados
        existing_var_list = []
        list_id = []
        for item in cart_item:
            existing_variation = item.variations.all()
            existing_var_list.append(list(existing_variation))
            list_id.append(item.id)

        if product_variation in existing_var_list:
            index = existing_var_list.index(product_variation)
            item_id = list_id[index]
            item = CartItem.objects.get(product=product, id=item_id)
            item.quantity += 1
            item.save()

        else:
            item = CartItem.objects.create(product=product, quantity=1, cart=cart)

            if len(product_variation) > 0:
                item.variations.clear()
                item.variations.add(*product_variation)

            item.save()

    else:

        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        if len(product_variation) > 0:
            cart_item.variations.clear()
            cart_item.variations.add(*product_variation)

        cart_item.save()

    return redirect('cart')


def remove_cart(request, product_id, cart_item_id):

    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)

    try:

        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()

    except:
        pass

    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):

    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)

    cart_item.delete()

    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    context = {'total': total, 'quantity': quantity, 'cart_items': cart_items}

    return render(request, 'store/cart.html', context)

store/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from carts.models import CartItem
from carts.views import _cart_id
from category.models import Category
from store.models import Product
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator


def store(request, category_slug=None):

    categories = None
    products = None
    category = Category.objects.all()
    if category_slug is not None:

        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()

    else:

        products = Product.objects.all().filter(is_available=True)
        paginator = Paginator(products, 4)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()

    context = {'products': paged_products, 'product_count': product_count, 'categories': category}

    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=product).exists()

    except Exception as e:
        raise e

    context = {'product': product, 'in_cart': in_cart}

    return render(request, 'store/product_detail.html', context)


def search(request):

    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            # Q serve para selecionar mais de um campo para fazer pesquisa
            # icontains serve para ver se a keyword está no campo que eu quero
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) |
                                                                        Q(product_name__icontains=keyword))
            product_count = products.count()

        context = {'products': products, 'product_count': product_count}

    return render(request, 'store/store.html', context)

templates/store/cart.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
        {% if not cart_items %}
        <div class="text-center">
            <h2>Cart is empty</h2>
            <br>
            <a href="{% url 'home' %}" class="btn btn-primary btn-block">Continue Shopping</a>
        </div>
        {% else %}
        <div class="row">
            <aside class="col-lg-9">
              <div class="card">
                <table class="table table-borderless table-shopping-cart">
                  <thead class="text-muted">
                    <tr class="small text-uppercase">
                      <th scope="col">Product</th>
                      <th scope="col" width="120">Quantity</th>
                      <th scope="col" width="120">Price</th>
                      <th scope="col" class="text-right" width="200"> </th>
                    </tr>
                  </thead>
                  <tbody>

                  {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <figure class="itemside align-items-center">
                                <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
                                  <figcaption class="info">
                                      <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                                      <p class="text-muted small">
                                          {% if cart_item.variations.all %}
                                            {% for item in cart_item.variations.all %}
                                                {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }}<br>
                                            {% endfor %}

                                          {% endif %}
                                      </p>
                                  </figcaption>
                            </figure>
                        </td>
                        <td>
                            <div class="col">
                                <div class="input-group input-spinner">
                                    <div class="input-group-prepend">
                                        <a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-minus"><i class="fa fa-minus"></i></a>
                                    </div>
                                    <input type="text" class="form-control" value="{{ cart_item.quantity }}">
                                    <div class="input-group-append">
                                        <form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
                                            {% csrf_token %}
                                            {% for item in cart_item.variations.all %}
                                            <input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst }}">
                                            {% endfor %}
                                            <button class="btn btn-light" type="submit" id="button-plus"><i class="fa fa-plus"></i></button>

                                        </form>
                                    </div>
                                </div>
                            </div>

                        </td>
                        <td>
                            <div class="price-wrap">
                                <var class="price">${{ cart_item.sub_total }}</var>
                                <small class="text-muted"> ${{ cart_item.product.price }} each </small>
                            </div> <!-- price-wrap .// -->
                        </td>
                        <td class="text-right">
                        <a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a>
                        <a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Are you sure you want to remove this item?')" class="btn btn-danger"> Remove</a>
                        </td>
                    </tr>
                  {% endfor %}

                  </tbody>
                </table>

              <div class="card-body border-top">
                  <p class="icontext"><i class="icon text-success fa fa-truck"></i> Free Delivery within 1-2 weeks</p>
              </div> <!-- card-body.// -->

              </div> <!-- card.// -->

                  </aside> <!-- col.// -->
              <aside class="col-lg-3">

              <div class="card">
              <div class="card-body">
                      <dl class="dlist-align">
                        <dt>Total price:</dt>
                        <dd class="text-right">${{ total }}</dd>
                      </dl>
                      <hr>
                      <p class="text-center mb-3">
                          <img src="{% static '../static/images/icons/pay-visa.png' %}" height="26">
                      </p>
                      <a href="#" class="btn btn-primary btn-block"> Make Purchase </a>
                      <a href="{% url 'home' %}" class="btn btn-light btn-block">Continue Shopping</a>
              </div> <!-- card-body.// -->
              </div> <!-- card.// -->
            </aside> <!-- col.// -->
        </div> <!-- row.// -->
    </div>
    {% endif %}
</section>

{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<title>Product</title>

<!-- jQuery -->
<script src="{% static '../js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static '../js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static '../css/bootstrap.css" rel="stylesheet' %}" type="text/css"/>

<!-- Fonticons -->
<link href="{% static '../fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">
<link href="{% static '../fonts/feathericons/css/iconfont.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static '../fonts/material-icons/css/materialdesignicons.css' %}" rel="stylesheet" type="text/css" />

<!-- custom style -->
<link href="{% static '../css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static '../css/responsive.css' %}" rel="stylesheet" />

<!-- custom javascript -->
<script src="{% static '../js/script.js' %}" type="text/javascript"></script>


</head>
<body>

<section class="section-content padding-y bg">
	<div class="container">
		<!-- ============================ COMPONENT 1 ================================= -->
		<div class="card">
			<div class="row no-gutters">
				<aside class="col-md-6">
		<article class="gallery-wrap">
			<div class="img-big-wrap">
			   <a href="#"><img src="{{ product.images.url }}"></a>
			</div> <!-- img-big-wrap.// -->
			<div class="thumbs-wrap">
			  <a href="#" class="item-thumb"> <img src="{{ product.images.url }}"></a>
			</div> <!-- thumbs-wrap.// -->
		</article> <!-- gallery-wrap .end// -->
				</aside>
	<main class="col-md-6 border-left">
		<form action="{% url 'add_cart' product.id %}" method="POST"> {% csrf_token %}
			<article class="content-body">
				<h2 class="title">{{ product.product_name }}</h2>
				<div class="mb-3">
					<var class="price h4">${{ product.price }}</var>
				</div>

				<p>{{ product.description }}</p>

				<hr>
					<div class="row">
						<div class="form-group col-md flex-grow-0">
							<label><b>Quantity</b></label>
							<div class="input-group mb-3 input-spinner">
							  <div class="input-group-prepend">
								<button class="btn btn-light" type="button" id="button-plus"> + </button>
							  </div>
							  <input type="text" class="form-control" value="1">
							  <div class="input-group-append">
								<button class="btn btn-light" type="button" id="button-minus"> &minus; </button>
							  </div>
							</div>
						</div> <!-- col.// -->
						<div class="form-group col-md">
							<dl class="row">
								<dt class="col-md-12"><b>Choose color</b>
									<select type="button" name="color" class="form-control col-md-8" required>
										<option value="" disabled selected>Select</option>
										<!-- _set.all serve para pegar todas os itens -->
										{% for i in product.variation_set.colors %}
										<option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
										{% endfor %}
									</select>
								</dt>
							</dl>
						</div>
						<div class="form-group col-md">
							<label><b>Select size</b></label>
								<dl class="row">
										<select type="button" name="size" class="form-control col-md-8">
											<option value="" disabled selected>Select</option>
											{% for i in product.variation_set.sizes %}
											<option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
											{% endfor %}
										</select>
									</dt>
								</dl>
						</div> <!-- col.// -->
					</div> <!-- row.// -->
					{% if product.stock <= 0 %}
					<h5 class="text-danger">Out of stock</h5>
					{% else %}
						<button type="submit" class="btn  btn-outline-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i></button>
					{% endif %}
			</article> <!-- product-info-aside .// -->
		</form>
	</main> <!-- col.// -->
	</div> <!-- row.// -->
	</div> <!-- card.// -->
	<!-- ============================ COMPONENT 1 END .// ================================= -->
	</div>
</section>
<br><br>
{% endblock %}

templates/store/store.html
{% extends 'base.html' %}

{% block content %}


<section class="section-content padding-y">
	<div class="container">
		{% if 'search' in request.path %}
			<h2>Search result</h2>
		{% else %}
		{% endif %}
		<div class="row">
			<aside class="col-md-3">
			<br>
			<br>
			<br>
			<div class="row">
				<aside class="col-md-12">
					<nav class="card">
						<ul class="menu-category">
							<li><a class="dropdown-item" href="{% url 'store' %}">All products</a></li>
							{% for category in categories %}
							<li><a href="{{ category.get_url }}">{{ category.category_name }}</a></li>
							{% endfor %}
						</ul>
					</nav>
				</aside> <!-- col.// -->
			</div> <!-- row.// -->

			</aside> <!-- col.// -->
			<main class="col-md-9">

		<header class="border-bottom mb-4 pb-3">
				<div class="form-inline">
					<span class="mr-md-auto"><b>{{ product_count }}</b> Items found </span>
					<select class="mr-2 form-control">
						<option>Latest items</option>
						<option>Trending</option>
						<option>Most Popular</option>
						<option>Cheapest</option>
					</select>
				</div>
		</header><!-- sect-heading -->
		{% if products %}
		{% for product in products %}
		<article class="card card-product-list">
			<div class="row no-gutters">
				<aside class="col-md-3">
					<a href="{{ product.get_url }}" class="img-wrap">
						<span class="badge badge-danger"> NEW </span>
						<img src="{{ product.images.url }}">
					</a>
				</aside> <!-- col.// -->
				<div class="col-md-6">
					<div class="info-main">
						<a href="{{ product.get_url }}" class="h5 title"> {{ product.product_name }}  </a>

						<!--<div class="rating-wrap mb-3">
							<ul class="rating-stars">
								 <li style="width:80%" class="stars-active">
									<i class="fa fa-star"></i> <i class="fa fa-star"></i>
									<i class="fa fa-star"></i> <i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
								</li>
								<li>
									<i class="fa fa-star"></i> <i class="fa fa-star"></i>
									<i class="fa fa-star"></i> <i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
								</li>
							</ul>
							<div class="label-rating">7/10</div>
						</div>// --> <!-- rating-wrap.// -->


						<p> {{ product.description }} </p>
					</div> <!-- info-main.// -->
				</div> <!-- col.// -->
				<aside class="col-sm-3">
					<div class="info-aside">
						<div class="price-wrap">
							<span class="price h5"> ${{ product.price }} </span>
							<!--<del class="price-old"> $198</del>// -->
						</div> <!-- info-price-detail // -->
						<p class="text-success">Free shipping</p>
						<br>
						<p>
							<a href="{{ product.get_url }}" class="btn btn-primary btn-block"> Details </a>
						</p>
					</div> <!-- info-aside.// -->
				</aside> <!-- col.// -->
			</div> <!-- row.// -->
		</article> <!-- card-product .// -->
		{% endfor %}
		{% else %}
			<div>
				<h2>No products found</h2>
			</div>
		{% endif %}

		<nav aria-label="Page navigation sample">
			{% if products.has_other_pages %}
			<ul class="pagination">
				{% if products.has_previous %}
					<li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
				{% else %}
					<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
				{% endif %}

				{% for i in products.paginator.page_range %}
					{% if products.number == i %}
						<li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
					{% else %}
						<li class="page-item"><a class="page-link" href="?page{{i}}">{{ i }}</a></li>
					{% endif %}
				{% endfor %}

				{% if products.has_next %}
					<li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
				{% else %}
					<li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
				{% endif %}
			</ul>
			{% endif %}
		</nav>

			</main> <!-- col.// -->

	</div>


	</div> <!-- container .//  -->
</section>
{% endblock %}